#OpenStack version number
version: 14
#Nuage Release and format is <Major-release, use '-' instead of '.'>-<Minor-release>-<Updated-release>
release: 5-4-1-u4
#Tag for Nuage container images
tag: latest
#Undercloud Local Regstry IP Address
local_registry: 192.168.24.1:8787
#List of Nuage containers
nuage_images: ['heat-api-cfn', 'heat-api', 'heat-engine', 'horizon', 'neutron-server']