heat_template_version: queens
description: 'Noop Extra Pre-Deployment Config'
parameters:
  server:
    type: string
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  RepoBaseURL:
    type: string
    default: ''
    description: Base URL for the repos
  GPGKeys: 
    type: string
    default: ''
    description: GPGKeys URL comma seperated. 
  RepoAVRSURL:
    type: string
    default: ''
    description: A/O/VRS URL for the repos
    tags:
      - role_specific

resources:
  RoleParametersValue:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        map_replace:
          - map_replace:
            - Repo_OVS_URL: RepoAVRSURL 
            - values: {get_param: [RoleParameters]}
          - values:
              RepoAVRSURL:  {get_param: RepoAVRSURL}
  NodeSpecificConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: baseurl
      - name: ovsurl
      - name: gpgkey
      config: |
        #!/bin/sh
        #  Enable all the repos
        #  Base Repo
        rm -rf /etc/yum.repos.d/nuage.repo
        touch /etc/yum.repos.d/nuage.repo
        echo "[BaseNuageRepo]" >> /etc/yum.repos.d/nuage.repo 
        echo "name=baserepo" >> /etc/yum.repos.d/nuage.repo 
        echo "baseurl=$baseurl" >> /etc/yum.repos.d/nuage.repo 
        echo "enabled = 1" >> /etc/yum.repos.d/nuage.repo 
        echo "gpgcheck = 1" >> /etc/yum.repos.d/nuage.repo 
        echo "gpgkey = $gpgkey" >> /etc/yum.repos.d/nuage.repo 
        echo "[Nuage]" >> /etc/yum.repos.d/nuage.repo 
        echo "name=nuage" >> /etc/yum.repos.d/nuage.repo 
        echo "baseurl=$ovsurl" >> /etc/yum.repos.d/nuage.repo 
        echo "enabled = 1" >> /etc/yum.repos.d/nuage.repo 
        echo "gpgcheck = 1" >> /etc/yum.repos.d/nuage.repo 
        echo "gpgkey = $gpgkey" >> /etc/yum.repos.d/nuage.repo 


  NodeSpecificDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: NodeSpecificDeployment
      config: {get_resource: NodeSpecificConfig}
      server: {get_param: server}
      input_values:
        baseurl: {get_param: RepoBaseURL}
        ovsurl: {get_attr: [RoleParametersValue, value, Repo_OVS_URL]}
        gpgkey: {get_param: GPGKeys}
outputs:
  deploy_stdout:
    value: "None"
