parameter_defaults:
  # This section is where deployment-specific configuration is done
  #
  # NOTE: (Since Rocky)
  # ControlPlaneSubnetCidr: It is no longer a requirement to provide the
  #                         parameter. The attribute is resolved from the
  #                         ctlplane subnet(s).
  # ControlPlaneDefaultRoute: It is no longer a requirement to provide this
  #                           parameter. The attribute is resolved from the
  #                           ctlplane subnet(s).
  # EC2MetadataIp: It is no longer a requirement to provide this parameter. The
  #                attribute is resolved from the ctlplane subnet(s).
  #

  # Customize the IP subnet to match the local environment
  StorageNetCidr: '172.16.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageAllocationPools: [{'start': '172.16.1.4', 'end': '172.16.1.250'}]
  # Customize the VLAN ID to match the local environment
  StorageNetworkVlanID: 30


  # Customize the IP subnet to match the local environment
  StorageMgmtNetCidr: '172.16.3.0/24'
  # Customize the IP range to use for static IPs and VIPs
  StorageMgmtAllocationPools: [{'start': '172.16.3.4', 'end': '172.16.3.250'}]
  # Customize the VLAN ID to match the local environment
  StorageMgmtNetworkVlanID: 40


  # Customize the IP subnet to match the local environment
  InternalApiNetCidr: '172.16.2.0/24'
  # Customize the IP range to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '172.16.2.4', 'end': '172.16.2.250'}]
  # Customize the VLAN ID to match the local environment
  InternalApiNetworkVlanID: 20


  # Customize the IP subnet to match the local environment
  TenantNetCidr: '172.16.0.0/24'
  # Customize the IP range to use for static IPs and VIPs
  TenantAllocationPools: [{'start': '172.16.0.4', 'end': '172.16.0.250'}]
  # Customize the VLAN ID to match the local environment
  TenantNetworkVlanID: 50
  # MTU of the underlying physical network. Neutron uses this value to
  # calculate MTU for all virtual network components. For flat and VLAN
  # networks, neutron uses this value without modification. For overlay
  # networks such as VXLAN, neutron automatically subtracts the overlay
  # protocol overhead from this value.
  TenantNetPhysnetMtu: 1500


  # Customize the IP subnet to match the local environment
  ExternalNetCidr: '10.0.0.0/24'
  # Customize the IP range to use for static IPs and VIPs
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '10.0.0.4', 'end': '10.0.0.250'}]
  # Gateway router for routable networks
  ExternalInterfaceDefaultRoute: '10.0.0.1'
  # Customize the VLAN ID to match the local environment
  ExternalNetworkVlanID: 10


  # Customize the IP subnet to match the local environment
  ManagementNetCidr: '10.0.1.0/24'
  # Customize the IP range to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '10.0.1.4', 'end': '10.0.1.250'}]
  # Gateway router for routable networks
  ManagementInterfaceDefaultRoute: '10.0.1.1'
  # Customize the VLAN ID to match the local environment
  ManagementNetworkVlanID: 60


  # Define the DNS servers (maximum 2) for the overcloud nodes
  # When the list is not set or empty, the nameservers on the ctlplane subnets will be used.
  # (ctlplane subnets nameservers are controlled by the ``undercloud_nameservers`` option in ``undercloud.conf``)
  DnsServers: ['135.1.1.111']
  BondInterfaceOvsOptions: "mode=active-backup"
