# Heat environment file which can be used to enable
# Nuage backend on the compute, configured via puppet
resource_registry:
  OS::TripleO::Services::ComputeNeutronCorePlugin: ../puppet/services/neutron-compute-plugin-nuage.yaml

parameter_defaults:
  NuageActiveController: '0.0.0.0'
  NuageStandbyController: '0.0.0.0'
  NuageBridgeMTU: '9000'
  NovaIPv6: 'True'
  NuageMetadataProxySharedSecret: 'default'
  NuageNovaApiEndpoint: 'default_endpoint'
  NovaOVSBridge: 'alubr0'
  NovaComputeLibvirtType: 'kvm'
  NovaComputeLibvirtVifDriver: 'nova.virt.libvirt.vif.LibvirtGenericVIFDriver'